name: flutter_news
description: A Hacker News client in flutter

dependencies:
  flutter:
    sdk: flutter
  url_launcher: '^0.4.0'
  timeago: '^1.0.0'
  shared_preferences:
  intl: '>=0.14.0 <0.15.0'
  intl_translation: '>=0.14.0 <0.15.0'
  html_unescape:
    git:
      url: git://github.com/andresaraujo/html_unescape.git
      ref: patch-1

flutter:
  uses-material-design: true
  assets:
    - assets/mock_data/askstories.json
    - assets/mock_data/beststories.json
    - assets/mock_data/jobstories.json
    - assets/mock_data/newstories.json
    - assets/mock_data/showstories.json
    - assets/mock_data/topstories.json
    # Stories
    - assets/mock_data/14411126.json
    - assets/mock_data/14410533.json
    - assets/mock_data/14411067.json
    - assets/mock_data/14411499.json
    - assets/mock_data/14409760.json
    - assets/mock_data/14411297.json
    - assets/mock_data/14408859.json
    - assets/mock_data/14406874.json
    - assets/mock_data/14409553.json
    - assets/mock_data/14411338.json
    - assets/mock_data/14410489.json
    - assets/mock_data/14410201.json
    - assets/mock_data/14410846.json
    - assets/mock_data/14409534.json
    - assets/mock_data/14409269.json
    - assets/mock_data/14405179.json
    - assets/mock_data/14410357.json
    - assets/mock_data/14409019.json
    - assets/mock_data/14409210.json
    - assets/mock_data/14403911.json
    - assets/mock_data/14411150.json
    - assets/mock_data/14409797.json
    - assets/mock_data/14407207.json
    - assets/mock_data/14407393.json
    - assets/mock_data/14409950.json
    # Comments
    - assets/mock_data/14411458.json  # L1
    - assets/mock_data/14411669.json  #  L2
    - assets/mock_data/14411734.json  #   L3
    - assets/mock_data/14414333.json  #  L2
    - assets/mock_data/14411945.json
    - assets/mock_data/14411398.json
    - assets/mock_data/14411594.json
    - assets/mock_data/14412057.json
    - assets/mock_data/14411204.json
    - assets/mock_data/14411534.json
    - assets/mock_data/14411534.json
    - assets/mock_data/14411534.json
    - assets/mock_data/14411534.json
